name = "daggerheart-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "daggerheart-uploads"

[env.dev]
vars = { ENVIRONMENT = "development" }
